### PR TITLE
Add a button with link to fdroid in README.md

### PR DESCRIPTION
**Pull request by Poussinou**

### CODE REVIEW

**Comment by tananaev** [comment]
I don't like that it needs resizing. Images look blurry.

**Comment by Poussinou** [comment]
I think the buttons are too bigs if they aren't resized.

**Comment by tananaev** [comment]
Yes, they are. That's why we need to find better images.

**Comment by tananaev** [comment]
I think there are SVG images that we can use and they will scale without blurring.

**Comment by tananaev** [comment]
Merged. Thanks for pull request.

**Pull request merged**
