### PR TITLE
Use vector icons.

### PR DESCRIPTION
**Pull request by garyvdm**
This patch removes the png icons, and replaces them with vector icons. This should make it easier to add/change icons in the future, as a single file can provide all the multi-density images.

Since we are targeting an older minSdkVersion, the vectors are converted to png at build time, as per https://developer.android.com/studio/write/vector-asset-studio.html

I've tried to make sure that the images look as close to the originals as possible.
screenshot_20171213-135558

### CODE REVIEW

**Comment by tananaev** [comment]
Where did you get the images? I can probably provide original SVG for the Traccar logo.. and other icons are from Google material icons set.

**Comment by garyvdm** [comment]
A small advantage of this is I use `android:fillColor="@color/primary"` in the vector files, so changing the colour of the icons is as simple as changing the `color/primary` resource.

**Comment by tananaev** [comment]
Here is the original source for the icon with shadow:

https://www.dropbox.com/s/cwtcw2t9eibi1ux/logo-with-shadow.svg?dl=0

**Comment by garyvdm** [comment]
I've rebased this off master, and added a small fix needed to make it work with the support library v27.

**Comment by tananaev** [comment]
Merged, thanks. Would you be able to implement same thing for Traccar Manager?

**Comment by garyvdm** [comment]
> Merged, thanks. Would you be able to implement same thing for Traccar Manager?
Sure. I'll do that today.

**Comment by garyvdm** [comment]
I'm very sorry, this patch has an issue with. The icon does not show on older SDKs. I'm sure I tested it on older SDK's.  Maybe my testing faulty.

I'm working on a fix.

**Comment by tananaev** [comment]
I'm assuming there is the same problem with manager as well, correct?

**Comment by garyvdm** [comment]
> I'm assuming there is the same problem with manager as well, correct?
Yes

**Pull request merged**
