### PR TITLE
Adding a car mode with different update frequencies

### PR DESCRIPTION
**Pull request by britiger**
This pull request detect the movement while driving an increase the frequency, it sound be also a solution for #58. If you activate the mode you can set a different frequency. This will be used if the new position moved more than the given distance in the settings. If you don't move more than distance you set in given timeout it will you the normal frequency.

### CODE REVIEW

**Comment by tananaev** [comment]
Thanks for pull request, but it doesn't really look like a generic solution to a problem. It's a very specific use-case. It also requires user to switch manually between modes. Is that correct? Are users actually going to do that?

**Comment by britiger** [comment]
You only need to enable car mode once. If you car is parked, the clients transmitts the standard frequency eg. 300 sec. If the clients gets the next location and the distance is higher than treshold you set, the clients switches automatic to the frequency of the car mode e.g. 3 sec. If you now park your car and the position is within the distance you set it will change the frequency back to standard, 300 sec.

**Comment by tananaev** [comment]
I still think it would be better to implement some more generic logic. For example this:

https://www.traccar.org/forums/topic/suggestion-implementing-polyline-simplification-in-traccar-client/

**Comment by luke-jr** [comment]
@tananaev The advantage of the solution used by @britiger here is that the GPS won't be activated at all while the device is stationary, thus reducing battery usage.

**Comment by tananaev** [comment]
@luke-jr, how would that work? You still need a GPS fix to know that you are stationary.

**Comment by luke-jr** [comment]
@tananaev It polls the GPS every 300 seconds in "stationary mode", and when it notices its distance has changed, it updates the polling interval to 3 seconds. And then adjusts it back to 300 seconds when you've remained stationary for a while again. So the first time may be delayed up to 5 minutes, but from then until you stop again gets the "micro-updates". IMO this is a good compromise between battery life and detailed updates.

(All durations are configurable of course)

**Comment by tananaev** [comment]
That makes some sense, but that's not what this pull request is for.

**Comment by luke-jr** [comment]
It's not? That's what it looked like to me. What am I missing?

**Comment by tananaev** [comment]
As far as I can tell, there is manual switch for switching between two modes.

**Comment by luke-jr** [comment]
https://github.com/tananaev/traccar-client-android/pull/188/files#diff-4ecac1d3a509af90183387880715a5a0R105 seems to automatically change the modes.

**Comment by tananaev** [comment]
Looks like you are right. The code is very confusing and needs a lot of cleaning before it can be accepted.

**Pull request closed without merging**
