### PR TITLE
Display actual values in preferences

### PR DESCRIPTION
**Pull request by redge76**
Hi,
Don't you think it's better to display the actual values without forcing the user "click" on the item?
(i only updated the English version of strings.xml. But I think even with the original text, It is fine.)
redge

### CODE REVIEW

**Comment by tananaev** [comment]
I thought about it when I originally implemented the app. I think summary info is more useful than the actual value. The only exception is IMEI number which user needs to see to enter on the server side.

**Comment by redge76** [comment]
Just that the summary does not explain much. (because there is not much to explain ...)
Original title :     Server port
Original summary:   Tracking server TCP port

My new title :    "Server TCP port"  
new summary : the port...
  (I mean it quite obvious that it is the *tracking* server)

Original title: Server address
Summary: Domain name or IP address
The summary does not bring much. Only that you can also enter an IP.
So that's why the new title is :  Server name or IP address

So by moving the little additional info in the summary to the title, we can also display the value.
But I let you decide. It's your app :-)

**Comment by tananaev** [comment]
My main issue is that I would have to get all translations again. It's not easy and I don't see that much value in this change to be worth the effort.

**Comment by redge76** [comment]
OK. that a good point...

**Comment by tananaev** [comment]
We can keep the pull request open in case in future I would have to get some new strings translated and then merge it.

**Pull request closed without merging**
