### PR TITLE
Get service notification to show. Tweek settings.

### LINKED ISSUE #299: Clicking on service notification should go to app activity
**Steps to reproduce:**

- Start service
- Open notification bar
screenshot_20171212-073721
- Click on service notification

**Actual Result:**

- Android app settings page is opened, with option to Stop app, or uninstall

**Desired Result:**

- App activity should be opened, so that one can easily stop service, view status logs, or change settings.
screenshot_20171212-073731

### PR DESCRIPTION
**Pull request by garyvdm**
Fixes #299 

This gets the foreground service notification to show correctly. With a bit of playing, discovered that to get the notification to work, `setSmallIcon` must be called, and `setPriority` needs `PRIORITY_LOW` or higher.

I also tweaked some of the parameters for notification to try follow the design guidelines.

Clicking on the notification now takes you to the `MainActivity`.

screenshot_20171213-081400

### CODE REVIEW

**Comment by tananaev** [comment]
Interesting... have you tested earlier version of Android? What does it look like there?

**Comment by garyvdm** [comment]
I will do so.

**Comment by tananaev** [comment]
I would recommend to test at least on API 15 (earliest supported) and 22 (one of the most popular versions).

**Comment by garyvdm** [comment]
The notification only shows from API 25 onwards.  

If I remove the use of the `HideNotificationService`, and use `TrackingService` instead, then the notification shows for all versions (styling needs to changes for some of the older apis.)

For my use cases hiding the notification does not make sense, but I know my use cases are not the same as others. 

Would you consider a patch that disables use use of `HideNotificationService` in the `regular`/`google` product flavours, and enables it for the `hidden` flavour?

**Comment by tananaev** [comment]
What is your use case and why do you need notification?

**Comment by garyvdm** [comment]
Use case is to track my self, and others on long distance cycling rides.

Would prefer to have the notification so that I can easily check if the service is running, without needing to open the `MainActivity`.

**Comment by tananaev** [comment]
Most people don't want to see notification, even if they know that there is a app running in the background. It just creates clutter in the notification area.

I have merged this pull request. As for `HideNotificationService`, we can create a new issue to see what people think about it.

**Comment by tananaev** [comment]
Thanks for pull request.

**Pull request merged**
