### PR TITLE
For hidden flavor, make notificaion not open the app when clicked, use different icon.

### PR DESCRIPTION
**Pull request by garyvdm**
I only recently figured out how to select build variants, an hence be able to test my changes to the hidden flavor. 

I realised my previous change is a bit of a regression for the hidden flavor. This patch tweeks the notification that shows when the notification can't be hidden, i.e. SDK >= 25.  Changes include: 

- Don't have a intent, so clicking on the notification does not do anything,
- Make the notification icon a settings icon
- Remove as much text from the notification as possible.

Screenshot:
screenshot_20171214-122347

### CODE REVIEW

**Comment by tananaev** [comment]
I have idea. What if instead of having no intent we use settings intent, so that it goes into standard Android settings. I think it would be even better.

What about the icon for non-hidden version? Is it going to use standard app icon?

**Comment by garyvdm** [comment]
> I have idea. What if instead of having no intent we use settings intent, so that it goes into standard Android settings. I think it would be even better.

I will do that.

> What about the icon for non-hidden version? Is it going to use standard app icon?

It's using this file for the icon: https://github.com/tananaev/traccar-client-android/blob/master/app/src/main/res/drawable/ic_stat_notify.xml

Screenshot: 
screenshot_20171213-081400

**Comment by tananaev** [comment]
Great, thanks.

**Comment by tananaev** [comment]
Merged, thanks.

**Pull request merged**
